### ISSUE TITLE
Media Card: Display the "Block Emphasis" options on Mobiles

### ISSUE THREAD

**Issue by madalingorbanescu** [pixelgrade/nova-blocks#159]
With every update on Nova Blocks, the Media Card is starting to be one of the main blocks. Using this block, you can achieve really nice layouts on desktops. Given the fact that a lot of users are using mobiles to access websites, we can improve a little this block on mobile.

This is how Media Card block looks on desktop: https://share.getcloudapp.com/GGuk50QJ
And this is how Media Card looks on mobiles: https://share.getcloudapp.com/wbu0Le6p

We are not showing the background for content, or for block. My suggestion is to add background color on block, on mobiles and in that way there can be seen a difference from section to section.

With background, the block will look like this: https://share.getcloudapp.com/5zu1O5Lz

What do you think @georgeolaru?

**Comment by georgeolaru** [comment]
Good catch @madalingorbanescu! I think the backgrounds and colors could be a nice improvement to the consistency across devices.

My main concern is particularly regarding **the spacing** and how we will be able to space the [block (content)+(media)] using the same spacing system from the desktop.

I draw a quick mockup on how the spacing should look like for the Media Card. Let's give it the first spin by making sure _the vertical spacing_ is the same between `content` and `media` (twice the side space):

![image](https://user-images.githubusercontent.com/1632775/81682876-f87c8180-945d-11ea-81ff-4ec11cb3c68f.png)

**Comment by razwan** [comment]
Working on the Posts Collection block I came across this issue and made some changes to keep the block emphasis styles in #166. 

However, at the moment, the spacing in pretty inconsistent across themes ([Rosa2](https://user-images.githubusercontent.com/1633371/82818615-a8fb7400-9ea7-11ea-9bc3-c08539c8bf5a.png), [Twenty Twenty](https://user-images.githubusercontent.com/1633371/82818696-c29cbb80-9ea7-11ea-86f4-a832833fb78c.png), [Newspack Joseph](https://user-images.githubusercontent.com/1633371/82818933-2e7f2400-9ea8-11ea-9587-ea3623be5c1e.png)) 

I woudln't change anything regarding spacing in the plugin or the theme for now, since the work done for #87 would affect that. That being said, I believe that merging #166 is enough to close this issue, and we could maybe go ahead and adjust spacing after that happens.

What do you think, @georgeolaru?

**Comment by georgeolaru** [comment]
@razwan It's looking _great_ on Rosa2 and _good enough_ on the mentioned examples — I encourage to close this issue if this was your only concern.

While reviewing, I noticed two things:

1. **Vertical spacing** seems to be mostly smaller and inconsistent, excepting the margin-top of a content area with basic emphasis: 
![image](https://user-images.githubusercontent.com/1632775/82895861-9ba0c100-9f5d-11ea-8ca6-f68d949a1804.png)
→ [Figma Mockup](https://www.figma.com/file/LkOxQKLMqMpZwBJQiTmmuiYK/Plugin-Nova-Blocks?node-id=2095%3A2891)

2. Now the **Block** emphasis is preserved which makes the Content background switch on mobile. Instead, I suggest to use the **Content** area emphasis level to control the Block area on mobile. 

![image](https://user-images.githubusercontent.com/1632775/82894970-25e82580-9f5c-11ea-91ec-72ea1d367bd3.png)

If you would like to discuss this further, just let me know.

**Comment by razwan** [comment]
1. I will touch on that, but what I was trying to say is that when we will close #87 these changes will not have any impact any more since spacing will be dictated by the block's **Block Top Spacing** attribute etc.

2. There are some use cases where the **Content Area Emphasis** is irrelevant on mobile, like the one below, where the content is basic, and the block is highlighted. But if I understand correctly we should try to keep the visual aspect of the content area on mobile.

![Screenshot 2020-05-27 at 10 25 38](https://user-images.githubusercontent.com/1633371/82990207-7c10a380-a004-11ea-9df2-a065bb4d1f00.png)
