### ISSUE TITLE
[Posts Collection] Add Reading Time Meta

### ISSUE THREAD

**Issue by madalingorbanescu** [pixelgrade/nova-blocks#226]
Add a new option for Primary and Secondary Meta, called _Reading Time_.
This meta will show the user an estimated read time.

We can use the average reading speed of an adult (265 WPM), considering that [Medium is using the same number](https://help.medium.com/hc/en-us/articles/214991667-Read-time).

**Comment by vladolaru** [comment]
Regarding the reading speed, that is an average and average on _native_ English speakers. But we are not talking only about native English speakers (we ourselves are not). 

A more _human-centered_ approach would be a range of time like The Correspondent does it (e.g. https://thecorrespondent.com/722/how-progressives-could-still-win-the-21st-century-by-yanis-varoufakis/916745568288-5f9f9acc) taking a fast (native) reading rate of around 280 WPM and a slow rate (non-native) of around 180 WPM. These are ballpark rates since the actual rate depends on the type of material you are reading (technical or non-technical). But I say they are better than one-size-fits-all.

My 2 cents.

**Comment by madalingorbanescu** [comment]
Hey @vladolaru,

Thank you for your suggestion 😇

I totally agree with you on this approach. However, because this reading time is shown on cards and not inside articles, I am not sure that this is the way to go.

Here is how smaller cards with reading time will look:

![image](https://user-images.githubusercontent.com/46342490/97301885-f918a100-1860-11eb-8128-c1d627659499.png)
![image](https://user-images.githubusercontent.com/46342490/97302074-3b41e280-1861-11eb-9ea5-7fc08bf94a71.png)

Considering that we can also show 2 metas (reading time + author for example), I think we should stick you the initial proposal, following the format `x min read`.

@georgeolaru I would love to hear your opinion on this.

**Comment by georgeolaru** [comment]
Great points @vladolaru and I'm in favor of taking into consideration the nuances of people's different reading speeds within a set of variables (their native language vs the content language, proficiency, etc).

Within a list of articles (eg. archive), I assume that the _Reading Time_ is used relatively to compare between their lengths (eg. one is twice as long as the other) and the _precission_ is not that relevant.

Considering this _context_ I would keep using the "short" version (`24 min read`) on Posts Cards block and hold in mind to use the "extended" form (`Reading time 9 - 12 minutes`) for the Article page, where I think accuracy is more important.

---
Now regarding the implementation, @vladolaru do you have any concerns regarding the **performance**? I might be wrong but it seems that the reading time is computed on-the-go for each post. Could a _caching_ system be involved or I'm overthinking?

**Comment by vladolaru** [comment]
@georgeolaru Regarding performance, the calculations are not that difficult. And on the frontend they are served through PHP, not JS. So I don't see any problems.
