### ISSUE TITLE
Create a Conversation System for Community Building

### ISSUE THREAD

**Issue by madalingorbanescu** [pixelgrade/nova-blocks#253]
Original proposal by @georgeolaru for Pixelgrade.com:
---

I want to create a refined version of the default Comments system and use it as a component across the board: through the Upstairs Blog, Upstairs Community, and Pixelgrade Themes (Rosa2). 

The objective is to focus on extending the value of the article's topic by people's contributions, NOT on the maximum number of comments. We want to create a place for _discourse_ and less a place to just say "yay" or "meh".

> I go to a website and read an article. Man, that was really great. I’d like to comment and ask the author a question. I scroll down… 384 comments. Ugh. Screw this.
—  [Cultivating Conversations](https://v4.jasonsantamaria.com/articles/cultivating-conversations/) by Jason Santa Maria

Promoting meaningful and in-depth conversations, the comments section should serve as an [addendum](https://en.wikipedia.org/wiki/Addendum) to the initial author's thoughts, therefore putting on the same table multiple viewpoints and experiences, including critics.

> A _like_ can’t go anywhere, but a _compliment_ can go a long way. Passive positivity isn’t enough; active positivity is needed to counterbalance whatever sort of collective conversations and attention we point at social media. Otherwise, we are left with the skewed, inaccurate, and dangerous nature of what’s been built: an environment where most positivity is small, vague, and immobile, and negativity is large, precise, and spreadable.
— [Like compliment](https://frankchimero.com/blog/2019/like-compliment/) by Frank Chimero

With those things in mind, I manage to create a few mockups so we can use it for guidance.

### → [Figma Mockups](https://www.figma.com/file/x3hxMaLar6GA2ZtDOHjO7q/LT-Pattern-Library?node-id=355%3A156)

---
# Implementation

In the [Single page anatomy](https://user-images.githubusercontent.com/1632775/98508893-f65a7a80-2268-11eb-8ee3-9a5e63d5f182.png), the **Comments Area** will be an independent section at the end of the page:

![image](https://user-images.githubusercontent.com/1632775/98508872-ec387c00-2268-11eb-8183-bc5707e0be78.png)

## Conversation Starter (Block)
To get the conversation started I suggest helping the contributors and give them a way to go. You might remember the [event](https://3.basecamp.com/3285391/buckets/1248673/messages/1905071144) that we had with the team a while ago in the Pixelgrade garden, where @oanafilip used some questions to untie the conversation — it worked great and we should strive for something similar.

![image](https://user-images.githubusercontent.com/1632775/98509040-36b9f880-2269-11eb-99ab-922e2a627d5f.png)

Technically, the _Conversation Starter_ is an optional section where a user could write a question or concern to kickstart the conversation. It will usually be the author, but not necessarily (eg. Upstairs Community) — so an option to set the _Conversation Starter_ author is needed.

### Backend:
There should be a "Conversation Starter" panel below the editor with the following fields:

| Option  | Description                                     |
|---------|-------------------------------------------------|
| Content | Write your content                              |
| Author  | Select author                                         |
| Subtitle   | A question by %author%, author of this article: |

After a brief discussion with @vladolaru, we decided that a future-proof option is to have this as a Gutenberg **block** within Nova Blocks plugin.

### Frontend: 
- it resembles the styling of a Highlighted/Featured comment

## Comment Form
I took inspiration from the _Reviews_ system, set everything in one column, and used longer titles and descriptions for each field.

![image](https://user-images.githubusercontent.com/1632775/98514514-3d993900-2272-11eb-92f1-f9f894befe93.png)

### Guidelines:
- The Comment Form shows by default before the Comments List
  - If there are more than 5 comments, it shows again at the end of the Comment List.
- It uses a design pattern called [Expandable Input](http://ui-patterns.com/patterns/expandable-input), as follows:
   - By default, only the avatar and message field should appear
   - The full version appears only when entering the "focus mode" by clicking on the message field
      - This is the use-case where unregistered users could post comments. In the future, we would like to make it available only for registered members, so an [overlay](https://user-images.githubusercontent.com/1632775/98514383-088ce680-2272-11eb-95fc-586d3471b892.png) might trigger to sign in.
- There should be a custom field called **Credential** used as a way for contributors to represent their experience on the answers they write. We have something similar on the _Reviews_ system, but it's a [common](- It would be nice to have a minimal **editor** (like [Trix](https://github.com/basecamp/trix)) for the message to help contributors organize their thoughts.) pattern to bring more context about the author.
- It would be nice to have a minimal **editor** (like [Trix](https://github.com/basecamp/trix)) for the message to help contributors organize their thoughts.

## Comments List

![Screenshot2020-11-09 at 10 01](https://user-images.githubusercontent.com/1632775/98514804-b7c9bd80-2272-11eb-9d99-4385f6e15e0e.gif)

### Guidelines
- One level deep for threaded comments; I think could be set within WordPress.
- Author comments are highlighted only by changing the badge color
- An option for the Editors to Highlight/Feature relevant comments and get them more exposure. This could stay behind the "More" dropdown menu and simply add a class in the frontend.

---

## Progress Pipeline
- [x] Conversation starter
   - [x] Backend functionality @vladolaru 
   - [x] Frontend styling 
- [x] Comment Form
   - [x] Frontend styling 
   - [x] Add Credential field @vladolaru 
- [x] Comments List
   - [x] Frontend styling 
   - [x] An option to highlight relevant comments @vladolaru 

---
_Note: The issue was initially opened in [Storechild](https://github.com/pixelgrade/storechild/issues/552), but because we chose to develop this functionality as a Gutenberg block, we have decided that this repo is better suited for the issue._

**Comment by georgeolaru** [comment]
I will leave this resource in case we need it for the full setup:

[Falcon](https://github.com/humanmade/Falcon) project for Email Notifications (by Human Made) via [Jeremy Felt](https://jeremyfelt.com/2020/09/23/a-checklist-for-how-id-like-comments-to-work-in-wordpress/) article on _A checklist for how I’d like comments to work in WordPress_
> Caspar: Late to the party, but I thought this might be interesting in terms of notifications: https://github.com/humanmade/Falcon
>
> I not only allows somewhat granular notifications for new posts and comments, but also supports comment-by-email, similar to GitHub issues.
>
> I use a fork on my blog that additionally enables comment notifications on private posts (which I make accessible for subscribers).

**Comment by vladolaru** [comment]
Other (maybe) useful resources that I've come across:

- https://wordpress.org/plugins/elevated-comments/
- https://wordpress.org/plugins/webmention/
- https://wordpress.org/plugins/wp-ajax-edit-comments/
- https://wordpress.org/plugins/subscribe-to-comments-reloaded/
- https://wordpress.org/plugins/simple-comment-editing/
- https://wordpress.org/plugins/yoast-comment-hacks/
- https://wordpress.org/plugins/comment-mention/
- https://wordpress.org/plugins/truncate-comments/
- https://wordpress.org/plugins/limit-comments-and-word-count/

I am not proposing we use any or all of these plugins. Just that I found them interesting for having a full-fledged comments experience and I might end up using some or borrowing ideas from them.

**Comment by vladolaru** [comment]
I am going to need help with small styling changes or improvements. I will document them bellow:
- [ ] **Allow for missing avatars everywhere** since these can be disabled via the "Discussion" WP dashboard section. I've added the `no-avatar` CSS class everywhere we use an avatar.
- [ ] **Conversation Starter:** allow for missing avatar and/or subtitle (I've added the `no-avatar` and `no-subtitle` CSS classes when that happens)
- [ ] **Conversation Starter:** Support bold, italic, underline, links (basically all the core "data" allowed tags https://github.com/WordPress/WordPress/blob/master/wp-includes/kses.php#L418-L446 ) in content and subtitle.
- [ ]

**Comment by vladolaru** [comment]
Now a few more tasks, but for me at this moment:
- [ ] Support pagination: this is important since many AJAX plugins rely on present navigation links to load up more comments.
- [ ] ...

**Comment by vladolaru** [comment]
@madalingorbanescu Regarding moving the comment form on scroll, good job. But you should add it after the div with the ID `second-comment-form-marker`. If this div is not present, there should be no moving of the comment form.

**Comment by vladolaru** [comment]
Also @madalingorbanescu I see you've made it that the more dropwdown closes on click anywhere else, but it should also close on a second click on More.

**Comment by oanafilip** [comment]
👏 **Congrats to all!** I'm keen to see how this conversation system will get traction and evolve. It looks promising and aligns perfectly with how we do things at Pixelgrade: in-depth, meaningful, performant.

While I'm confident that this framework will stimulate valuable conversations among our readers, I think it's essential to set boundaries and define a _language_ around them. Let me shed some light.

I genuinely believe that words have an incredible power, and dictate most of the results. How we speak, how we write, what words we choose can draw a huge difference. Imagine talking with a kid of four years, explaining why some folks are rich and some live in poverty. You can use slang (inflation, gross product, unemployment, and such), or you can refer through more common words and expressions (some people live in a country where there aren't many natural resources, it's hard to build in dessert, etc.).

My point here is that there's a difference between _conversations, comments, and questions_. Similar to reviews, feedback, and testimonial (you can refresh your memory with this [article](https://pixelgrade.com/upstairs/creating-a-customer-review-system-for-your-site/)), such nuances will impact the outcome.

This being said, I suggest sticking to _conversations_ since it is more in-tune with who we are and what values we convey at Pixelgrade. Into a conversation, people hear each other, listen fully, expect their turn to engage, and such. Comments have less skin in the game; it's easier to comment but far harder to enroll in a profound dialogue. Questions, on the other hand, are a tool to kick-off worthwhile conversations.

So, my suggestion would be to fine-tune the existing content as follows:
cc @georgeolaru, @vladolaru, @madalingorbanescu  

- **Conversations**: I don't see any value in listing the number "7 with 4 replies"; articles with one conversation only are less valuable? I don't think so.

- **What's your comment or question?**: I would change it with _What's your curiosity related to what you just read?_

- **What's your background around this topic?**: I would change it with _What's your expertise around this topic?_ (also, I suggest switching the spots between the example and the placeholder)

- **What's your name?**: I would add **What's your full name?**

These insights came from a place of care from someone who puts a high price on worthwhile conversations and believes we need far more honest and profound dialogues in the digital space. 

I am around if you want to follow-up on this one and take it even further. Cheers!

![Screenshot 2020-12-11 at 15 46 20](https://user-images.githubusercontent.com/17414378/101912198-1794ea80-3bca-11eb-8cca-63191d23207e.png)

**Comment by georgeolaru** [comment]
@oanafilip I think we all agree that _language_ is important, especially in this context where communication is involved, and we put the effort to make it better than the provided default. Great analogy with the kids and how we could shape the language so they can understand! Thanks for stepping in!

---

Now, the (WordPress) context is a bit different and pose some constraints that we should take into consideration.

There is a [standard](https://wordpress.org/support/article/comments-in-wordpress/) naming defined within WordPress and I would not want to go too far from it: it is also used across the admin panel (eg. `comments`, `replies`) and if we change it on the frontend it will create _confusion_ for the user.

I'm willing to put the Comments system under the "Conversation" umbrella (which is usually referred to as "Discussion" in WordPress) as it is closer to a _human conversation_. Other than that I think we should keep using the "comment" and "reply" as _child_ of the "Conversation" system. 

---

@vladolaru I think you added some touches to the copy and here is my input, based on @oanafilip suggestions:

**1. Conversations Quantity**: 
- I do think we should keep in place this meta information, not as a way to estimate an article value, but as a way to estimate the extent of the conversation. I understand that for Pixelgrade.com this is not even needed, but I believe there is value for other sites, especially when this information is used on the archive page.
- I don't think we should divide the total number of comments by their way of replying (as _a parent_ to the article or as _a child_ to another comment) as the whole conversation should be around the main topic (the article) and all the comments are replies and variations to that topic.
- My suggestion is to stick with the original "X comments" formula which we could use consistently on the archives

**2. What's your comment or ~question~ curiosity?**
- Here is the "message" field where the user gives its input, be it a question, a curiosity, a story, a new perspective etc.
- "Curiosity" the same as "question" limit the scope of the message and I think we should keep the "comment" and add "curiosity" instead of "question"

**3. What's your ~background~ expertise around this topic**
- Great suggestion! "Expertise" is more explicit than "background"

**4. What's your ~full~ name?**
- I think it's more natural to ask someone for their name and let her decide how they want to be called (eg. by first name, full name, nickname, anonymous or fake name)
- If we want to go a step further, I think we could use something like "How do you want to be called?" — but simply "name" seems good enough for me.

---
Hope it makes sense! But if you have further feedback, please drop it here.

**Comment by vladolaru** [comment]
Thank you both, @oanafilip and @georgeolaru for pitching in with your suggestions. We all aim for making things better, that's for sure.

Now, to keep things moving, _I will take it upon myself_ to have the final call on what happens with **the comments system in Nova Blocks** (the general one) while leaving adjustments for _our use of it_ on Pixelgrade.com for another place and time. With that being said, here are the conclusions:

**1. Conversations Quantity:** 
**We will retain the comments count meta-information** with _the option_ to differentiate between top-level comments and replies as I think this plays well with the concept of _conversations_ (a conversation being a top-level comment plus all its replies). More so, replies in conversations may be hidden by default (in some design scenarios) to allow for a smoother scanning of the main topics of conversation (the top-level comments).

**2. What's your comment or question/curiosity?:** 
**Curiosity** is a pretty loaded word as it entails further exploration of the article topic via questions for the article author. I think this is a pretty specific scenario where comments are used (mainly) by the author as a Q&A with his or hers audience. 
_The more general scenario_ is where comments are a place for readers to _add_ to the story, to express their (arguments for) agreement or disagreement with the article, to bring forth side-narratives sparked by the main one, etc. 
This is a conscious choice and it should be made by each site. The system will provide out-of-the-box _a neutral stance_ that _could_ work for most audiences.

**We will stick, for now, with: "What's your comment or question?"**
**We will skip the description with the Example and use it as a placeholder instead.**

**3. What's your background/expertise around this topic?**
**Expertise** is a word that entails a certain bureaucratic certification or depth in a topic gained through _a great deal of experience._ I can understand (somewhat) why The Correspondent might use it, but I think it limits the scope of possible contributors to conversations, and not in a good way.
More so, I see in it the chance of _belittling people_ that lack expertise in the current topic (while they may have in others). 

To _exemplify_ what I am talking about: 
- take an article talking about website performance; 
- a small restaurant owner lands on the article; 
- he or she wants to ask a question and gets put off by "what is my expertise around this topic?"; 
- "I have no expertise in web performance! I barely know a little bit about WordPress." 

But if it would have been about "background" (a more neutral term that encompasses "expertise" and "experience") he or she would have had no trouble stating: "Site owner" (not expertise but a state of affairs), "Restaurant site owner", or "Prospective site owner".

I haven't realized it by now but, considering [a random article](https://thecorrespondent.com/698/dear-news-media-stop-covering-the-us-as-if-its-a-democracy/67612483356-c8106075) on The Correspondent, here are the expertise people have shared:

- Non US citizen obsessed with US politics
- Student Artificial Intelligence
- Philosophically inclined family physician
- germanist
- analyst of Min. of Foreign Affairs reports since 2007
- bachelor of public management / tax specialist
- disabled vet, beekeeper, farmer, grandfather, agitator/activist
- Stakeholder
- Someone who has thought very deeply about what authentic courtesy is.
- American living in Europe
- Lived in the US for aproxx 2 years between 1987 and 1989.
- Engineer
- Etc.

There are definitely some certifications and expertise in there, but most are other types of background people thought useful to tag their thoughts. Some funny :)

So, as long as this commenter attribute is contextualized to the current topic (not a general set of skills like on LinkedIn) to give some context to the other conversation participants, "expertise" is not the proper word. **We will stick with "background".**

**4. What's your name?**
_The full name_ is too official. It's necessary for invoicing and other paper trails, but I believe people will decide how they want to identify in the conversation, based on their specific cultural and social background. 
**We will use just "name".**

---

I hope my conclusions make sense and thank you all for pitching in.

**Comment by vladolaru** [comment]
For the first version of the conversation system, I believe we've gone long enough (even a bit further). **We will finish up what remains here.**

I am going to open a new issue for tracking taking things even further :D

**Comment by vladolaru** [comment]
@madalingorbanescu The "Conversation Starter" content needs more attention to styling text styles like bold, italic, strikeout, etc.
![Screenshot 2020-12-21 at 10 32 31](https://user-images.githubusercontent.com/8830539/102756196-2c1a7500-4378-11eb-9ca7-3659927b0be4.png)

**Comment by georgeolaru** [comment]
Even if I think it's better to encourage users to use plain text for _the starter question_ and not employ another level of the hierarchy — It's bizarre that the text styles (em, strong) change the font sizes too. 🤔

**Comment by vladolaru** [comment]
I agree @georgeolaru. As stated in the _inline documentation:_ `You can use HTML elements like <b>, <i>, <a> to put some structure or emphasis on your message. Best that you don't overdo it.`

![Screenshot 2020-12-21 at 14 23 49](https://user-images.githubusercontent.com/8830539/102776879-3187b780-4398-11eb-8fa4-d730fe2e2d97.png)

**Comment by georgeolaru** [comment]
Great @vladolaru! Dynamic tags are the best :D

**Comment by vladolaru** [comment]
@madalingorbanescu A few more styling and behavior issues:

- [ ] I added styling for **comments links focus state** (dotted thin line) but I think we should have this site-wide (on storechild). Please check if my modification is what is needed.
- [ ] The "More" dropdown should also **open on focus** (with Tab) on any menu items.
- [ ] The [above](https://github.com/pixelgrade/nova-blocks/issues/253#issuecomment-748845788) Conversation Starter issue.

**Comment by madalingorbanescu** [comment]
Hey @vladolaru,

First things first — the issue with font sizes for bold and italic was related to storechild, so I will fix it there.

I've also pushed a small change that will handle More dropdown state on focus. 

Now regarding styling for link focus state, in my opinion, links focus state should not be styled by the plugin.  Link focus styling should be the same site-wide, not different along sections. Considering that, I will tackle this issue on storechild repo.

**Comment by vladolaru** [comment]
OK @madalingorbanescu That sounds good. Thanks

**Comment by vladolaru** [comment]
And with that being said, **we can close here and continue on #260**

Good work, everyone!
