### ISSUE TITLE
Small styling issues that need attention 

### ISSUE THREAD

**Issue by alinclamba** [pixelgrade/nova-blocks#283]
There seems to be a line between the 1st block and the 2nd block (under the arrow); also, there's a thin white line in the button (only for the mobile version).

Screenshot from the site (https://infuse.onefifthmedia.com.au/):

![rosa-nova_buttons](https://user-images.githubusercontent.com/6790170/107012080-32867400-67a1-11eb-9f08-577d946dbba0.jpg)

**Notes:**
- pc: windows 10 (see a line under arrow)
- phone: android  (see button problem and a borderline under arrow)
- browser: chrome
- there's no such line under the arrow when I use Mac.
-

**Comment by madalingorbanescu** [comment]
Hey @alinclamba,

This issue seems to be specific to Rosa2, not Nova Blocks, however, I wouldn't label it as an issue.

This is happening because we are using [fluid typography](https://pixelgrade.com/upstairs/creating-true-fluid-web-typography/) and spacing. We are heavily using `calc()`, and the returned result can be a number like 17.3251.

The problem arises from a different approach for subpixels calculations between browser, this is why on some browsers the lines are visible, while on some browsers there are no lines.
