### ISSUE TITLE
[Media Cards] The images are not displayed on Safari

### ISSUE THREAD

**Issue by alinclamba** [pixelgrade/nova-blocks#284]
When using the Safari browser, the images from **Media Cards Collection** block are not displayed.

![CleanShot 2021-02-05 at 12 10 01@2x](https://user-images.githubusercontent.com/6790170/107020243-4d5de600-67ab-11eb-9371-230242e0bffa.png)

Tested with **Safari 13.1.2** on **macOS High Sierra 10.13.6**,  Nova Blocks 1.8.1, and **Rosa2 1.8.1**.

**Comment by georgeolaru** [comment]
@alinclamba this seems to be related to an old similar issue https://github.com/pixelgrade/nova-blocks/issues/219

**Comment by alinclamba** [comment]
@georgeolaru yes, indeed. I forgot about that. However, the problem is that using **Rosa2 v1.5.0** (used for testing in that specific issue), the problem isn't occurring.🤔  

So now, with **Rosa2 v1.8.1**, the problem arises again. Maybe I should have reopened that issue instead of starting a new one; I can do it now if you think it's better.

**Comment by georgeolaru** [comment]
@alinclamba It's all right to keep both issues open and only to connect them with a reference link. It's possible that the situation to be different here.

@madalingorbanescu As you tested the previous issue, can you take a look here too?

**Comment by madalingorbanescu** [comment]
Hey,

I have tested the issue on my installation and I couldn't replicate it. However, @alinclamba allowed me to connect on his Mac, so I can inspect the issue.

The issue is not related to the Media Card block, but to Rosa2 Dark Mode. A function is returning an error and the JavaScript is not running anymore. In the picture shared by @alinclamba it can be seen that the sticky header is also broken:

![CleanShot 2021-02-05 at 16 20 45](https://user-images.githubusercontent.com/46342490/107045456-34b2f780-67ce-11eb-82ad-7d3ecd37c475.png)

Considering that, I am going to open a new issue on the Rosa2 repo, to address this issue.
