### ISSUE TITLE
[Open Hours] Compress Opening Hours not working

### ISSUE THREAD

**Issue by andreiungurianu** [pixelgrade/nova-blocks#288]
When I use the Overview display setting for the Open Hours block and enable the Compress Opening Hours block, all that happens is that the Day marked as closed moves to the bottom, but the other similar days do no compress.

**Update:** the option seems to be broken only when I use a comma to separate between days of the week that share the same time frame (e.g., mon, wed, thu 9-17). 

From the similar feature found in Osteria, the WordPress theme, I can see that having a comma should not be a problem for the compress options. Here's an example added in the [documentation](https://pixelgrade.com/docs/osteria/advanced-customizations/adding-opening-hours-system/) for the similar feature: ``mon, tues, wednesday 1015-2; f 12:00p until 2300;``

I'm using Rosa2 1.9.1, Nova Blocks 1.9.0, WordPress 5.6.1

https://user-images.githubusercontent.com/53944294/108043909-515ef300-704a-11eb-8d6d-789b7615c293.mp4

**Comment by georgeolaru** [comment]
I tested and the only time the `Compress Opening` option it's not working it's when days are separated by a comma. If anything else is used (eg. space or `to`) it seem to work well:
```
// 👎  Compres option don't work
monday, wednesday 9-17;

// 👍 Compres option work
monday to wednesday 9-17;
```
![Screenshot 2021-04-08 at 14-37](https://user-images.githubusercontent.com/1632775/114020287-19b93e00-9878-11eb-9c32-d6be44842bdd.gif)

I'm comfortable skipping this _edge case_ as a very limited part of users will run into it. 

@andreiungurianu  please take this into consideration and if you think it's worth the effort or this was a report from one of our users, reach Vlad and ask him to take a look. Otherwise, I suggest closing this issue.

**Comment by andreiungurianu** [comment]
@georgeolaru thanks for also testing this. My findings also shown that the `Compres Opening` feature does not work when a comma is used.

If you think that this edge case is not worth it, then I will close this issue and we can get back to it if customers will report a need for this fix.
