### ISSUE TITLE
[Header] CSS Error on Woocommerce's pages

### ISSUE THREAD

**Issue by fmopin** [pixelgrade/nova-blocks#300]
On Woommerce's pages, the header (navbar) is not like on the other pages. I couldn't identify why the header is changing only on woocommerce's pages.

Here a screenshot from a page where the header is working corectly : 

<img width="1438" alt="Header with the right comportment" src="https://user-images.githubusercontent.com/25414640/112504232-e2349700-8d8b-11eb-8502-3cb8565a1ad4.png">

Here a screenshot from a woocommere's page where it's not correct : 

<img width="1436" alt="Header on woocommerce pages" src="https://user-images.githubusercontent.com/25414640/112504505-245dd880-8d8c-11eb-8b20-1865c38fdc08.png">

**Comment by georgeolaru** [comment]
Thanks for reporting this, @fmopin! Can you share a few more details about your setup and the pages you encounter this error? Plugin version and live links would greatly help as I couldn't replicate this on my [end](https://demos.pixelgrade.com/rosa2/product-category/equipment/).

**Comment by fmopin** [comment]
Thanks for your answer. Here are the plugin versions : 

- Novablock : 1.9.0
- Pixelgrade Care : 1.7.14
- Woocommerce : Version 5.1.0

The website link is [https://francsburgers.com/](https://francsburgers.com/
)
I encounter this error only on woocommerce pages like the default shop page. If I create a wordpress page and use woocommerce widget to show products I don't have this error in the navbar.

Thanks for your help

**Comment by madalingorbanescu** [comment]
Hey @fmopin,

Thank you for providing more details. I have just take a look at your website and I have found the culprit. From what can I see, you are using a child theme with some custom CSS. A child theme is always a great idea to add some custom functionality or some custom CSS in this case. However, you need to be more careful with the custom CSS, because it can affect the theme's default styling.

In your case, you are using `.woocommerce img, .woocommerce-page img {
  width: 64.5%!important;
}`, using `.woocommerce` and `.woocommerce-page` in front of img, you are telling the browser that every image on a WooCommerce page should have a width of 64.5%. This CSS is breaking the navbar because the logo inside the Header is an image and its width will be set to 64.5%, which will cause some issues with the theme's CSS.

I am not sure what exactly you wanted to achieve with that CSS, but my suggestion would be to be more specific with your CSS rules and try to avoid using `!important`. For example, if you wanted the image inside products to have a width of 64.5% you should limit the CSS only to a gallery inside a single product, which will look something like this: `.woocommerce-product-gallery img { width: 64.5% }`

I would happily help you with some custom code if you tell me exactly what do you want to change.

**Comment by madalingorbanescu** [comment]
You're very welcome🤗
I am glad that I could help you in solving your problem.

I am going to close this issue now.
