### ISSUE TITLE
Hero Block: Crashes due to undefined hero_scroll_indicator

### ISSUE THREAD

**Issue by georgeolaru** [pixelgrade/nova-blocks#301]
I created a regular custom post type using the `Toolset` plugin, and whenever I insert a Hero block, it crashes with the following error on the console: 

![image](https://user-images.githubusercontent.com/1632775/112682139-59475980-8e78-11eb-9fc3-d7ac8707e2bc.png)

```
TypeError: Cannot read property 'novablocks_hero_scroll_indicator' of undefined
    at editor.min.js:12
    at lodash.min.js:97
    at lodash.min.js:53
    at ee (lodash.min.js:34)
    at qc (lodash.min.js:97)
    at editor.min.js:12
    at Object.useMemo (react-dom.min.js:216)
    at d.useMemo (react.min.js:32)
    at WithMetaAttributeSource((n)) (editor.min.js:12)
    at we (react-dom.min.js:84)
```

All the other blocks seem to work well, and even the `Hero` block works on `Pages` and `Posts,` so it might be something from the CPT that I'm missing.

To reproduce this behavior, you can go to the https://aplusnoima.pixelgrade.com/ website (I can provide the credentials).

@razwan Can you have a look over this issue? Thanks

**Comment by madalingorbanescu** [comment]
Hey,

After some diggings, it looks like the issue is related to the way custom post types are registered, not to Nova Blocks.
For the scroll indicator and scroll position, we are registering some metas for all posts. After reading some WordPress REST API documentation, I have found out this:

[_Note that for meta fields registered on custom post types, the post type must have custom-fields support. Otherwise, the meta fields will not appear in the REST API._](https://developer.wordpress.org/rest-api/extending-the-rest-api/modifying-responses/#read-and-write-a-post-meta-field-in-post-responses)

So, the solution to our problem was to just enable **Custom Fields** for the new custom post type.

**Comment by georgeolaru** [comment]
Great! Thanks for figure it out @madalingorbanescu
