### ISSUE TITLE
Maps Unable to load if wrong API key inserted 

### ISSUE THREAD

**Issue by QadiymStewart** [pixelgrade/nova-blocks#320]
Inserted wrong Google Maps API key now block won't load preview/settings anywhere on any page when used.
Provide option to update API key if failure occurs. Theme being used Rosa2.

![image](https://user-images.githubusercontent.com/28968495/121125790-2238e100-c7f5-11eb-8f29-e6bae51f74f6.png)

**Comment by razwan** [comment]
Hey Quadiym! 

Thank you for reporting the issue. We do have a fallback implemented in the **Map of the World** block when the API key the user has entered is invalid. The Google Maps API isn't keen on telling us what's wrong with the API key, but that's enough.


![Screenshot 2021-06-08 at 10 41 50](https://user-images.githubusercontent.com/1633371/121144150-6accba80-c846-11eb-8740-b9e57e1ef123.png)

Unfortunately I wasn't able to replicate the error you encountered. Maybe it's something specific about your setup that I'm missing?

However, since you're in a spot where you can't update the API key, you need to find a way to delete the `novablocks_google_maps_api_key` setting.

If you can't find a way around this issue, drop us an email at hello@pixelgrade.com and we'll try to help you out.

Best regards!
Răzvan

**Comment by QadiymStewart** [comment]
@razwan Where do I find this setting?

**Comment by razwan** [comment]
@QadiymStewart the only place in the UI where you could edit the maps API key is the Maps block.

You can also find the setting in the `wp_options` database table and delete it, or you could add a snippet of code (preferably to a child theme) and use [delete_option](https://developer.wordpress.org/reference/functions/delete_option/) to detele the setting from the DB. After the code has run and the setting has been deleted, remove the code and try to use the Maps block again. If you run into the same problem, please reach [support](https://pixelgrade.com/get-support/) and we will try to help you.

**Comment by georgeolaru** [comment]
Let's close this for now as I suppose that @QadiymStewart figure it out – if you still have any questions, please ping us back here. Thanks!
