### ISSUE TITLE
Remove Custom Navigation Block and replace it with core Navigation block

### ISSUE THREAD

**Issue by razwan** [pixelgrade/nova-blocks#48]
**Is your feature request related to a problem? Please describe.**
The [7.0.0 release](https://github.com/WordPress/gutenberg/releases/tag/v7.0.0) of Gutenberg comes with a new navigation block making the one in our plugin redundant.

**Describe the solution you'd like**
We should remove the navigation block in Nova Blocks and update the Header block to use the one in Gutenberg by the time this reaches core.

**Comment by madalingorbanescu** [comment]
More info about next WordPress releases can be found here: https://make.wordpress.org/core/2019/11/21/tentative-release-calendar-2020-2021/

**Comment by madalingorbanescu** [comment]
Maybe we should delay this change until the Navigation block is stable and will bring more good things.

Currently, the new block has options, that in my opinion are somehow problematic and the flow of adding menu & submenu items is not really on point.
- [ ] Alignment - Wide & Full Width - because we want to use this block inside Header Block, these options are not needed and currently the API is not allowing us to remove it.
- [ ] Text & Background Color - Not really helpful, because the header block background will not be changed and [something like this](https://user-images.githubusercontent.com/46342490/73431819-f167b280-4349-11ea-99a4-918f25763976.png) can be achieved, which is not something we want.

Here is a short video with Navigation Block and the current flow of adding menu and submenu items: https://share.getcloudapp.com/P8uYop0y

**Comment by razwan** [comment]
Closing this issue since it's been some time since this has been open. 
The current workflow seems simpler with our current navigation block and haven't encountered any issues since.
